### ISSUE TITLE
I think we can make some changes in the CSS styling to make the portfolio more attractive.

### ISSUE THREAD

**Issue by Rakshit-gen** [rodrigo-arenas/portfolio#4]
We can add shadows behind the cards and make them hover up on the homepage. We can also add some good background gradients in the project that can make it look more eye catching.

Please assign me this issue to improve.

**Comment by rodrigo-arenas** [comment]
Hi @Rakshit-gen thanks, 
It sounds interesting, as a general guidance, try to keep it minimalist and clean

**Comment by Rakshit-gen** [comment]
Thank you! I would make sure of that

**Comment by rodrigo-arenas** [comment]
The changes have been merged, thanks for the contribution! @Rakshit-gen

**Comment by Rakshit-gen** [comment]
> The changes have been merged, thanks for the contribution! @Rakshit-gen

Thanks alot for giving me the opportunity @rodrigo-arenas
